# Description:
# Says a random phrase
#
# Commands:
# kerminator worf me
# kerminator riker me
# kerminator picard me
# kerminator data me
# kerminator guinan me
#
# Notes:
#
# Author:
#   Brian Cain
#
#   Quotes provided by:
#     - Will Hopper
#     - Jeff Weiss
#     - Michael Prasuhn
#     - Nathaniel Smith
#

worfphrases = [
  "\"I look forward to walking through the jungle without a map and no idea what lies ahead.\" - Worf",
  "\"I do not play games.\" - Worf",
  "\"What are his rights in this century? Is there a, a trial? Or shall I execute him?\" - Worf",
  "\"Compared to Klingons, humans are fragile creatures.\" - Worf",
  "\"If you were a Klingon woman we would already be married.\" - Worf",
  "\"Sir, I have acted within the boundaries of Klingon law and tradition.\" - Worf",
  "\"He knows nothing of our ways!\" - Worf",
  "\"Captain, they will be incensed. My presence will be disruptive.\" - Worf",
  "\"As Head of Security, it is my duty to be... concerned.\" - Worf",
  "\"There is no honor in attacking the weak.\" - Worf",
  "\"The young people will see what it is to die - as a Klingon.\" - Worf",
  "\"Those are eloquent words, Tokath. But the truth is, I am being executed because I've brought something dangerous to your young people: knowledge.\" - Worf",
  "\"Do not deceive yourself. These people are not happy here. I see the sadness in their eyes.\" - Worf",
  "\"This is the moment where life and death meet. This is what we are - warriors.\" - Worf",
  "\"There is much you were never taught.\" - Worf",
  "\"I do not expect you to understand. You are a Romulan.\" - Worf",
  "\"I like my blood wine very young and very sweet.\" - Worf",
  "\"You could say 'thank you for saving my life'.\" - Worf",
  "\"All right, what do you want?\" - Worf",
  "\"I know what you are planning, sir. I will not be surprised.\" - Worf",
  "\"Worf, son of Mogh, does not break his word.\" - Worf",
  "\"In war there is nothing more honorable than victory.\" - Worf",
  "\"It is an instinct - the ability to look someone in the eyes and see the decision to kill. An instinct I no longer have.\" - Worf",
  "\"I find using a large and intimidating weapon like the bat'leth often leads to overconfidence.\" - Worf",
  "\"I do not apologize for what I have done.\" - Worf",
  "\"To lose something, one must first possess it.\" - Worf",
  "\"Questions are the beginning of wisdom, the mark of a true warrior.\" - Worf",
  "\"I went to Boreth to find my faith. For a time, I thought I had. But my heart is empty again. I do not know what to believe.\" - Worf",
  "\"If you were any other man, I would kill you where you stand.\" - Worf",
  "\"Computer, Lieutenant Commander Worf. Confirm auto-destruct sequence. Authorization: Worf, 3 7 Gamma Echo.\" - Worf",
  "\"Perhaps today *is* a good day to die! Prepare for ramming speed!\" - Worf",
  "\"Considering how many men you have known, that is quite a statement.\" - Worf",
  "\"May glory and honor follow you on your journey.\" - Worf",
  "\"I am Worf, son of Mogh. I now take my place as first officer. I serve the captain; but I stand for the crew.\" - Worf",
  "\"It is clear to me that none of you are worthy of my blood or my life. But I will stand for you; and together, we will restore honor to this ship and bring glory to the Empire.\" - Worf",
  "\"I considered letting them kill me. It seemed like the only way out.\" - Worf",
  "\"The Sword of Kahless!\" - Worf",
  "\"And if you had not been drunk and told a tavern full of people what you were planning, Toral would not have followed us here in the first place.\" - Worf",
  "\"The Sword is not meant for us. It was never our destiny to find it.\" - Worf",
  "\"When it is destined to be found... it will be.\" - Worf",
  "\"You rule without wisdom and without honor.\" - Worf",
  "\"Great men do not seek power. They have power thrust upon them.\" - Worf",
  "\"You have dishonored yourself and the Empire, and you are not worthy to lead the Council.\" - Worf",
  "\"What I say now, I say as a member of the House of Martok, not a Starfleet officer.\" - Worf",
  "\"You have not changed. You still expect people to solve the problems you create.\" - Worf",
  "\"I took the Starfleet emergency medical course. In a computerized simulation, I assisted in delivery of a human baby.\" - Worf",
  "\"Why do you mock me? Why do you wish to anger me?\" - Worf",
  "\"What burns in their eyes, fires my soul. I hear their words, and I see it all as it was. Part of me longs for that time.\" - Worf",
  "\"Yet in all you say, where are the words 'duty', 'honor', 'loyalty'? Without which a warrior is nothing!\" - Worf",
  "\"Really. I have no desire to leave the Enterprise.\" - Worf",
  "\"Romulan ale should be illegal.\" - Worf",
  "\"Captain, I do not think it is appropriate for a Starfleet officer to appear... naked.\" - Worf",
  "\"Men do not roar. Women roar. Then they hurl heavy objects... and claw at you.\" - Worf",
  "\"You are a worthy opponent.\" - Worf",
  "\"Klingons do not laugh.\" - Worf",
  "\"I have been told that patience is sometimes a more effective weapon than the sword.\" - Worf",
  "\"Who knows what the future will be, now that you have disrupted time. I may die tomorrow, or I may outlive you. But when I die, I would like an honorable death.\" - Worf",
  "\"I've an odd craving for the blood of a live Kolar beast.\" - Worf",
  "\"Klingon schools are designed to be difficult. The physical and mental hardships faced by the students are meant to build character and strength. However - if you wish to face a greater challenge, you may stay here with me. It would not be easy - for either of us. But perhaps we can face the challenge together.\" - Worf",
  "\"You are forbidden to join the House of Martok.\" - Worf",
  "\"I want you to assist me in performing the Hegh'bat ceremony. I want you to help me die.\" - Worf",
  "\"I do not welcome death, Commander.\" - Worf",
  "\"According to a tradition, I must take my life, after suffering this kind of injury. But I have decided to break with tradition. I have decided to live.\" - Worf",
  "\"I will still have to undergo a dangerous operation. I may still die. But it will not be by my own hand.\" - Worf",
  "\"I can see, our lives together will not be easy.\" - Worf",
  "\"We both know you do not belong here. You heard what I expect from the rest of the crew. Twice that I expect from you! Do we understand each other?\" - Worf",
  "\"What you're about to do entails a grave obligation. Do not accept it lightly.\" - Worf",
  "\"I will teach you what you need to know to be a warrior.\" - Worf",
  "\"The only real question is whether you believe in the legend of Davy Crockett or not. If you do, then there should be no doubt in your mind that he died a hero's death. If you do not believe in the legend, then he was just a man, and it does not matter how he died.\" - Worf",
  "\"Today was not my day to die.\" - Worf",
  "\"Be quiet! Or disappear back where you came from.\" - Worf",
  "\"I have wagered heavily in the ship's pool that you will take him past the sixth plateau.\" - Worf",
  "\"You can spend the rest of your life contemplating your failure as you labour alongside the other slaves in the ore processing center.\" - Worf",
  "\"First they demand we come out here, then they make us wait.\" - Worf",
  "\"Heroes of legends don't ache so much.\" - Worf",
  "\"You fight well - for a tailor.\" - Worf",
  "\"I have not had cause to complain, Captain.\" - Worf",
  "\"You have always used your knowledge of Klingon honor and tradition to get what you want from me.\" - Worf",
  "\"It is a cellular peptide cake... with mint frosting.\" - Worf",
  "\"Very good, Ensign. You have passed the challenge.\" - Worf",
  "\"Be certain you understand the risk you are taking. If you are captured...\" - Worf",
  "\"Colonel Kira and Chief O'Brien have completed another scan of the planet. As far as they can tell, he is not there.\" - Worf",
  "\"Spiritual possessions of this sort have been reported throughout Klingon history. It is called jat'yIn - the taking of the living by the dead.\" - Worf",
  "\"I have no fear of death.\" - Worf",
  "\"To die defending one's ship is the hope of every Klingon.\" - Worf",
  "\"See, when and if the captain becomes weak or unable to perform, it is expected that his honorable retirement should be assisted by his First. Your second officer will assassinate you for the same reasons.\" - Worf",
  "\"Find him and kill him!\" - Worf",
  "\"Death to the opposition!\" - Worf",
  "\"Thinking about what you can't control only wastes energy, and creates its own enemy. \" - Worf",
  "\"Only fools have no fear.\" - Worf",
  "\"I DO N... - I do not yell.\" - Worf",
  "\"A Klingon never breaks his word.\" - Worf",
  "\"You're just supposed to sit here?\" - Worf",
  "\"What is this place? How did a being like you get here?\" - Worf",
  "\"What a terrible way to die.\" - Worf",
  "\"In the Klingon MajQa ritual, there is nothing more important than receiving a revelation about your father.\" - Worf",
  "\"Join me in the R'uustai - the Bonding. You will become part of my family now and for all time. We will be brothers.\" - Worf",
  "\"I am not concerned with pleasure, Commander. I am a warrior.\" - Worf",
  "\"You are favored in the ship's pool.\" - Worf",
  "\"The object here is not to engage the creature in battle.\" - Worf",
  "\"We have played poker many times. I have never known you to bluff.\" - Worf",
  "\"When I pulled you from the plasma stream, you seemed... surprised I was alive.\" - Worf",
  "\"Are you a Klingon warrior or an Alverian dung beetle?\" - Worf",
  "\"Very convincing, Captain. But was it your intention to challenge me to a battle to the death?\" - Worf",
  "\"Next time, do not strike me with the back of your hand. Use your fist.\" - Worf",
  "\"Hm, yes - slightly reminiscent of night-blooming throgni, Captain. From home. Quite stimulating, wouldn't you say?\" - Worf",
  "\"Not the best way to meet your new captain.\" - Worf",
  "\"I hate questionnaires.\" - Worf",
  "\"There were no phasers in the 22nd century.\" - Worf",
  "\"Immobilized by the damn Ferengi!\" - Worf",
  "\"Pygmy cretins!\" - Worf",
  "\"What's going on? A ship has one bridge. One bridge! One Riker, one bridge!\" - Worf",
  "\"We are Starfleet officers; and Starfleet officers do not brawl with each other.\" - Worf",
  "\"You exaggerate - as usual.\" - Worf",
  "\"Grrr...\" - Worf",
  "\"Request permission to return to duty, sir.\" - Worf",
  "\"I do not see why it is necessary to wear these... ridiculous uniforms.\" - Worf",
  "\"You are an insulting, pompous fool! And if you were not an ambassador, I would disembowel you right here!\" - Worf",
  "\"You're just another weak Human afraid to face death!\" - Worf",
  "\"When a warrior dies in battle, his comrades stay with the body to keep away predators. That allows the spirit to leave the body when it is time to make the long journey to Sto-vo-kor.\" - Worf",
  "\"Ensign, no one is unstoppable. - Collimate the nadion emitters.\" - Worf",
  "\"I'm in charge of security!\" - Worf",
  "\"I still prefer Klingon operas.\" - Worf",
  "\"I killed it, and now I'm going to eat it.\" - Worf",
  "\"Captain, these are Romulans. They are without honor.\" - Worf",
  "\"It is an ancient Klingon tradition to commemorate an important event with a poem.\" - Worf",
  "\"When I served aboard the Enterprise, I always knew who were my allies and who were my enemies.\" - Worf",
  "\"I am certain that you will do whatever is necessary to complete your task.\" - Worf",
  "\"We do not discuss it with outsiders...\" - Worf",
  "\"Life is a great deal more complicated in this red uniform.\" - Worf",
  "\"I admire gall.\" - Worf",
  "\"Sir - may I say your attempt to hold the away team at bay with a non-functioning weapon was an act of unmitigated gall.\" - Worf",
  "\"The Klingon Empire will never yield!\" - Worf",
  "\"I like my species the way it is!\" - Worf",
  "\"The Borg have neither honor nor courage.\" - Worf",
  "\"You are cunning. You must have Klingon blood. But the battle is over.\" - Worf",
  "\"My mother is *never* on time. It is so... human of her.\" - Worf",
  "\"Cardassian politics are very complex.\" - Worf",
  "\"The Bajoran death chant is over two hours long.\" - Worf",
  "\"Kill it now. Make it appear that it died in the crash. Leave no evidence that we were ever here.\" - Worf",
  "\"Captain, the creatures are accelerating their approach. They are changing color!\" - Worf",
  "\"You can begin your experiment at any time!\" - Worf",
  "\"You're not talking, you're gossiping.\" - Worf",
  "\"You are lucky this is not a Klingon ship. We know how to deal with spies.\" - Worf",
  "\"I do not like doctors. Any doctors.\" - Worf",
  "\"Your ambushes would be more successful if you bathed more often!\" - Worf",
  "\"I am not expecting battle.\" - Worf",
  "\"Before him, there was no Klingon word for '*peace*-maker'.\" - Worf",
  "\"Human bonding rituals often involve a great deal of talking and dancing and crying.\" - Worf",
  "\"Things that would send cold chills down your spine, and wake you in the middle of the night. No, it is better you do not know. Excuse me.\" - Worf",
  "\"I don't understand their humor either.\" - Worf",
  "\"With all due respect... BEGONE!... sir.\" - Worf",
  "\"I would not become a terrorist. It would be dishonorable.\" - Worf",
  "\"My motives were personal, not political.\" - Worf",
  "\"Our Captain wants his junior officers to learn, learn, learn.\" - Worf",
  "\"Is there any indication that this is the work of an unknown intelligence?\" - Worf",
  "\"Something is waiting for us. I am not strong enough to fight it!\" - Worf",
  "\"Klingons do not allow themselves to be... 'probed'.\" - Worf",
  "\"Our gods are dead. Ancient Klingon warriors slew them a millennia ago. They were more trouble than they were worth.\" - Worf",
  "\"This was a great victory - one worthy of story and song.\" - Worf",
  "\"Any classified weapons knowledge you share with your captors will be considered treason.\" - Worf",
  "\"You will die without honor.\" - Worf",
  "\"You will never attain the 24th level of awareness.\" - Worf",
  "\"I do not care for telepaths; they make me... uneasy.\" - Worf",
  "\"Rest assured, Commander, we will be victorious, at whatever the cost.\" - Worf",
  "\"If winning is not important, then, Commander - why keep score?\" - Worf",
  "\"Trust is earned, not given away.\" - Worf",
  "\"It is Worf, madam, not Woof!\" - Worf",
  "\"A warrior does not complain about physical discomfort.\" - Worf",
  "\"Remember Rule of Acquisition No. 111: 'Treat people in your debt like family - exploit them!'\" - Worf",
]

rikerphrases = [
  "\"Mr. Worf, you do remember how to fire phasers?\" - Riker",
  "\"Earl Grey tea, watercress sandwiches... and Bularian canapés? Are you up for promotion?\" - Riker",
  "\"In all trust, there is the possibility for betrayal.\" - Riker",
  "\"We know you're dealing in stolen ore. But I wanna talk about the assassination attempt on Lieutenant Worf.\" - Riker",
  "\"But the probability of making a six is no greater than that of rolling a seven.\" - Riker",
  "\"Not if I weaken first.\" - Riker",
  "\"The Enterprise computer system is controlled by three primary main processor cores, cross-linked with a redundant melacortz ramistat, fourteen kiloquad interface modules.\" - Riker",
  "\"Did you come here for something in particular or just general Riker-bashing?\" - Riker",
  "\"Mr. Worf, you do remember how to fire phasers?\" - Riker",
  "\"Smooth as an android's bottom, eh, Data?\" - Riker",
  "\"I recommend you don't fire until you're within 40,000 kilometers.\" - Riker",
  "\"Well, I'll say this for him - he's sure of himself.\" - Riker",
  "\"We have a saboteur aboard.\" - Riker",
  "\"And blowing into maximum warp speed, you appeared for an instant to be in two places at once.\" - Riker",
  "\"Travel time to the nearest starbase?\" - Riker",
  "\"Besides, you look good in a dress.\" - Riker",
  "\"Did you come here for something in particular or just general Riker-bashing?\" - Riker",
  "\"Shields up! Rrrrred alert!\" - Riker",
  "\"Now we know what they mean by 'advanced' tactical training.\" - Riker",
  "\"We could cause a diplomatic crisis. Take the ship into the Neutral Zone\" - Riker",
  "\"Maybe we better talk out here; the observation lounge has turned into a swamp.\" - Riker",
  "\"The look in your eyes, I recognize it. You used to have it for me.\" - Riker",
  "\"Travel time to the nearest starbase?\" - Riker",
  "\"Ensign Babyface!\" - Riker",
  "\"Yesterday I did not know how to eat gagh.\" - Riker",
  "\"Computer, lights up!\" - Riker",
  "\"You're going to be an interesting companion, Mr. Data.\" - Riker",
  "\"Yes, absolutely, I do indeed concur, wholeheartedly!\" - Riker",
  "\"How long can two people talk about nothing?\" - Riker",
  "\"Sorry, Data.\" - Riker",
  "\"Fate protects fools, little children and ships named Enterprise.\" - Riker",
  "\"Well, I'll say this for him - he's sure of himself.\" - Riker",
  "\"Your head is not an artifact!\" - Riker",
  "\"Our neural pathways have become accustomed to your sensory input patterns.\" - Riker",
  "\"Fear is the true enemy, the only enemy.\" - Riker",
  "\"Some days you get the bear, and some days the bear gets you. Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody.\" - Riker",
  "\"Damage report!\" - Riker",
  "\"You did exactly what you had to do. You considered all your options, you tried every alternative and then you made the hard choice.\" - Riker",
  "\"For an android with no feelings, he sure managed to evoke them in others.\" - Riker",
  "\"Sure. You'd be surprised how far a hug goes with Geordi, or Worf.\" - Riker",
  "\"We finished our first sensor sweep of the neutral zone.\" - Riker",
  "\"I'm afraid I still don't understand, sir.\" - Riker",
  "\"About four years. I got tired of hearing how young I looked.\" - Riker",
  "\"Is it my imagination, or have tempers become a little frayed on the ship lately?\" - Riker",
  "\"I'll alert the crew.\" - Riker",
  "\"When has justice ever been as simple as a rule book?\" - Riker",
  "\"You bet I'm agitated! I may be surrounded by insanity, but I am not insane.\" - Riker",
  "\"They were just sucked into space.\" - Riker",
  "\"Why don't we just give everybody a promotion and call it a night - 'Commander'?\" - Riker",
  "\"A lot of things can change in twelve years, Admiral.\" - Riker",
  "\"Mr. Worf, you sound like a man who's asking his friend if he can start dating his sister.\" - Riker",
  "\"Travel time to the nearest starbase?\" - Riker",
  "\"Congratulations - you just destroyed the Enterprise.\" - Riker",
  "\"My oath is between Captain Kargan and myself. Your only concern is with how you obey my orders. Or do you prefer the rank of prisoner to that of lieutenant?\" - Riker",
  "\"I've had twelve years to think about it. And if I had it to do over again, I would have grabbed the phaser and pointed it at you instead of them.\" - Riker",
  "\"You enjoyed that.\" - Riker",
  "\"Your shields were failing, sir.\" - Riker",
  "\"This should be interesting.\" - Riker",
  "\"That might've been one of the shortest assignments in the history of Starfleet.\" - Riker",
  "\"Smooth as an android's bottom, eh, Data?\" - Riker",
  "\"Now, how the hell do we defeat an enemy that knows us better than we know ourselves?\" - Riker",
  "\"In all trust, there is the possibility for betrayal.\" - Riker",
  "\"Wouldn't that bring about chaos?\" - Riker",
  "\"What? We're not at all alike!\" - Riker",
  "\"I think you've let your personal feelings cloud your judgement.\" - Riker",
  "\"I will obey your orders. I will serve this ship as First Officer. And in an attack against the Enterprise, I will die with this crew. But I will not break my oath of loyalty to Starfleet.\" - Riker",
  "\"Worf, It's better than music. It's jazz.\" - Riker",
  "\"I suggest you drop it, Mr. Data.\" - Riker",
  "\"Then maybe you should consider this: if anything happens to them, Starfleet is going to want a full investigation.\" - Riker",
  "\"Well, that's certainly good to know.\" - Riker",
  "\"This is not about revenge. This is about justice.\" - Riker",
  "\"Commander William Riker of the Starship Enterprise.\" - Riker",
  "\"and attack the Romulans.\" - Riker",
  "\"This is the Enterprise. Return our personnel or face immediate reprisal.\" - Riker",
  "\"Who's your commanding officer?\" - Riker",
  "\"If we don't get our command computers back on-line soon, this -- whatever this is -- won't matter. We'll all be dead.\" - Riker",
  "\"Talk about going nowhere fast.\" - Riker",
  "\"Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody.\" - Riker",
  "\"I'll be sure to note that in my log.\" - Riker",
  "\"Damage report!\" - Riker",
  "\"Flair is what marks the difference between artistry and mere competence.\" - Riker",
  "\"The Enterprise computer system is controlled by three primary main processor cores, cross-linked with a redundant melacortz ramistat, fourteen kiloquad interface modules.\" - Riker",
  "\"I am your worst nightmare!\" - Riker",
]

picardphrases = [
  "\"Make it so.\" - Picard",
  "\"Engage.\" - Picard",
  "\"Tea. Earl Grey. Hot.\" - Picard",
  "\"After all, Number One, we're only mortal.\" - Picard",
  "\"I rather believe that time is a companion who goes with us on the journey and reminds us to cherish every moment because they'll never come again.\" - Picard",
  "\"What we leave behind is not as important as how we've lived.\" - Picard",
  "\"Reports of my assimilation are greatly exaggerated.\" - Picard",
  "\"The line must be drawn here! This far, no farther!\" - Picard",
  "\"And that is what it is to be human. To make yourself more than you are.\" - Picard",
  "\"Space, the final frontier. These are the voyages of the starship Enterprise. Its continuing mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before!\" - Picard",
  "\"If we're going to be damned, let's be damned for what we really are.\" - Picard",
  "\"Things are only impossible until they're not!\" - Picard",
  "\"The Prime Directive is not just a set of rules; it is a philosophy ... and a very correct one.\" - Picard",
  "\"No being is so important that he can usurp the rights of another.\" - Picard",
  "\"It is possible to commit no mistakes and still lose. That is not a weakness; that is life.\" - Picard",
  "\"Being first at any cost is not always the point.\" - Picard",
  "\"Let's make sure history never forgets the name ... Enterprise.\" - Picard",
  "\"You may test that assumption at your convenience.\" - Picard",
  "\"Imprisonment is an injury, regardless of how you justify it.\" - Picard",
  "\"I am Locutus of Borg. Resistance is futile.\" - Picard",
  "\"The road from legitimate suspicion to rampant paranoia is very much shorter than we think.\" - Picard",
  "\"Mr. Worf, villains who twirl their moustaches are easy to spot.\" - Picard",
  "\"I'd be delighted to offer any advice I have on understanding women. When I have some, I'll let you know.\" - Picard",
  "\"Seize the time... Live now! Make now always the most precious time. Now will never come again.\" - Picard",
  "\"There are four lights.\" - Picard",
  "\"No, I am not dead. Because I refuse to believe the afterlife is run by you. The universe is not so badly designed!\" - Picard",
  "\"There is a way out of every box, a solution to every puzzle; it's just a matter of finding it.\" - Picard",
  "\"All I can say is that although we have only been together for a short time, I know that you are the finest crew in the fleet.\" - Picard",
  "\"So, five-card stud, nothing wild. And the sky's the limit.\" - Picard",
  "\"On screen.\" - Picard",
  "\"...Open a channel.\" - Picard",
  "\"A bit less florid, Data...\" - Picard",
  "\"Duty. A starship captain's life is filled with solemn duty.\" - Picard",
  "\"Shut up.\" - Picard",
  "\"15 years I've been waiting to say that.\" - Picard",
  "\"What is all this about?\" - Picard",
  "\"You're not Reman!\" - Picard",
  "\"And if you had lived my life, you would understand my responsibility to the Federation.\" - Picard",
  "\"It amazes me how little you know yourself.\" - Picard",
  "\"You *are* me! The same noble Picard blood runs through our veins.\" - Picard",
  "\"We're about to find out, Data.\" - Picard",
  "\"I think it's time to try some unsafe velocities.\" - Picard",
  "\"Will Riker, you have been my trusted right arm for fifteen years.\" - Picard",
  "\"I appreciate you concern, Number One. But I've been itching to try the Argo.\" - Picard",
  "\"You have the bridge...\" - Picard",
  "\"Why am I here? Why have you done this?\" - Picard",
  "\"How can you be sure?\" - Picard",
  "\"Captain's personal log, supplemental.\" - Picard",
  "\"The crew has responded with the dedication I've come to expect of them.\" - Picard",
  "\"He wants to look me in the eye...\" - Picard",
  "\"Won't do what, Mr. Worf?\" - Picard",
  "\"Oh, come now. A big, handsome, strapping fellow like you? What can you be afraid of?\" - Picard",
  "\"Commander, when this is over, I owe you a drink.\" - Picard",
  "\"Don't worry, Number One, we'll still have you to Betazed with plenty of time to spare.\" - Picard",
  "\"I think of myself as an explorer.\" - Picard",
  "\"I was the first Picard to leave our solar system. It... caused quite a stir in the family.\" - Picard",
  "\"For now we see but through a glass darkly.\" - Picard",
  "\"Look at me, Shinzon. Your heart, your hands, your eyes are the same as mine.\" - Picard",
  "\"The honor was mine - Captain.\" - Picard",
  "\"No! Noooooooooo!\" - Picard",
  "\"I will not sacrifice the Enterprise.\" - Picard",
  "\"Data, I'm sure it's a fascinating experience, but perhaps you should deactivate your emotion chip for now.\" - Picard",
  "\"Data, there are times that I envy you.\" - Picard",
  "\"We are not going to lose the Enterprise. Not to the Borg. Not while I'm in command.\" - Picard",
  "\"Mr. Worf, do you remember your zero G combat training?\" - Picard",
  "\"Maximum setting. If you had fired this, you would have vaporized me.\" - Picard",
  "\"Six years ago, they assimiated me into their collective.\" - Picard",
  "\"In my century, we don't succumb to revenge.\" - Picard",
  "\"GET OUT!\" - Picard",
  "\"There was no way to save him.\" - Picard",
  "\"Mr. Worf... I regret some of the things I said to you earlier.\" - Picard",
  "\"As a matter of fact, I think you're the bravest man I have ever known.\" - Picard",
  "\"Mr. Data, lay in a course for the 24th century. I suspect our future is there waiting for us.\" - Picard",
  "\"That's not going to be easy.\" - Picard",
  "\"Try not to look at the stars. Keep your eyes on the hull.\" - Picard",
  "\"This is not about revenge.\" - Picard",
  "\"This is about saving the future of humanity!\" - Picard",
  "\"I don't have time for this.\" - Picard",
  "\"How about 'Jean-Luc'?\" - Picard",
  "\"Guilty of what?\" - Picard",
  "\"...Is it part of a Romulan plot, a ploy to start a war?\" - Picard",
  "\"No, Will, we can't! We have to save humanity!\" - Picard",
  "\"Red alert! All crew to battle stations!\" - Picard",
  "\"You're going to deny us travel through space?\" - Picard",
  "\"It's like the chicken and the egg, Will, the chicken and the egg!\" - Picard",
  "\"Well, I know that I am an old man and I am out of touch.\" - Picard",
  "\"Because it always works, Worf! Your problem is that you really *do* have a sense of honor, and you really *do* care about trust and loyalty. Don't blame me for knowing you so well.\" - Picard",
  "\"Q? What is going on here? Where is the anomaly?\" - Picard",
  "\"Oh, so that's why you married me\" - Picard",
  "\"No, I'm fine. I don't need rest.\" - Picard",
  "\"Beverly, I cannot believe that you are not willing to stay here until we...\" - Picard",
  "\"Mr. Data, you are a clever man - in any time period.\" - Picard",
  "\"This is not my time. I don't belong here.\" - Picard",
  "\"I'm not senile, you know. This did happen!\" - Picard",
  "\"I sincerely hope that this is the last time that I find myself here.\" - Picard",
  "\"Engage.\" - Picard",
  "\"Welcome to the Enterprise, Commander Riker.\" - Picard",
  "\"Fine. Let's hope they find you as tasty as they did their past associates.\" - Picard",
  "\"Data, how can you be programed as a virtual encyclopedia of human information without knowing a simple word like 'snoop'?\" - Picard",
  "\"What the hell? Children are not allowed on the bridge!\" - Picard",
]

dataphrases = [
  "\"But I am not capable of love.\" - Data",
  "\"The unidirectional nature of the time continuum makes that an unlikely possibility.\" - Data",
  "\"My programming may be inadequate to the task.\" - Data",
  "\"Lieutenant D'Sora just gave me what could be considered a very passionate kiss in the torpedo bay.\" - Data",
  "\"With regard to romantic relationships, there is no real me.\" - Data",
  "\"The tone of Commander Riker's voice makes me suspect that he is not serious about finding Ambassador T'Pel charming.\" - Data",
  "\"Friendly insults and jibes - another form of human speech that I am attempting to master.\" - Data",
  "\"I consider Geordi to be my best friend.\" - Data",
  "\"My hair does not require trimming, you lunkhead.\" - Data",
  "\"I am experimenting with friendly jibes and insults. It was not meant as a serious disparagement.\" - Data",
  "\"It is fortunate that I am able to perform my duties without emotional distractions.\" - Data",
  "\"I am not nervous. I am confused.\" - Data",
  "\"I have found Holmes' methodology of deductive reasoning to be quite useful.\" - Data",
  "\"Sir?\" - Data",
  "\"It appears to be a robotic arm\" - Data",
  "\"Do you think this is a wise course of action, sir?\" - Data",
  "\"I will always be puzzled by the human predilection for piloting vehicles at unsafe velocities.\" - Data",
  "\"I must deactivate you.\" - Data",
  "\"The codes stored in my neural net cannot be forcibly removed.\" - Data",
  "\"Captain, I believe I am feeling... anxiety. It is an intriguing sensation. A most distracting...\" - Data",
  "\"0.68 seconds sir. For an android, that is nearly an eternity.\" - Data",
  "\"My programming was not designed to process these sensations.\" - Data",
  "\"If you are referring to sexuality, I am... fully functional, programmed in... multiple techniques.\" - Data",
  "\"Good evening, ladies and germs.\" - Data",
  "\"Take my Worf. Please.\" - Data",
  "\"I believe that statement to be inaccurate, sir.\" - Data",
  "\"I told a joke.\" - Data",
  "\"Have I said something to offend you?\" - Data",
  "\"Then he is questioning my ability as a parent?\" - Data",
  "\"I have observed that in most species, there is a primal instinct to perpetuate themselves.\" - Data",
  "\"We must say goodbye now.\" - Data",
  "\" I am an android, not a robot.\" - Data",
  "\"Geordi thinks he is in command here - and he is correct.\" - Data",
  "\"Captain, the aliens have disappeared. And so has the shuttle.\" - Data",
  "\"Captain, there is no rational justification for this course.\" - Data",
  "\"I have no need for companionship. However, I do require some supplies.\" - Data",
  "\"I am a Frenchman.\" - Data",
  "\"Can I get you something? A beverage?\" - Data",
  "\"No, sir. But I will take your word for it. This is very amusing.\" - Data",
  "\"'Comedy stressing farce and horseplay'. Ah. This, no doubt, is a variation on 'pie in the face'.\" - Data",
  "\"The arrow impacted just above my sixth intercostal support, penetrating my secondary subprocessor.\" - Data",
  "\"Commander Riker is correct.\" - Data",
  "\"Is there a problem, Geordi?\" - Data",
  "\"Pardon me - but why is Lieutenant Barclay being referred to clandestinely as a vegetable?\" - Data",
  "\"You may... check me for rain if you wish, Counselor, but I assure you, I have no water in my...\" - Data",
  "\"I successfully planted a command into the Borg collective consciousness.\" - Data",
  "\"You are welcome, sir. If I can be of further assistance..\" - Data",
  "\"Interesting.\" - Data",
  "\"I came to the conclusion, it would be safer - and easier - to shut myself down and start again.\" - Data",
  "\"I once had what could be considered a crisis of the spirit.\" - Data",
  "\"Lieutenant, I must apologize for my inadvertent misconduct toward you.\" - Data",
  "\"Your restraint was most remarkable.\" - Data",
  "\"I believe, sir, that was the first time outsiders have witnessed the Klingon death ritual.\" - Data",
  "\"There is a bright side, Geordi. You will have me to talk to.\" - Data",
  "\"My positronic brain has several layers of shielding to protect me from power surges.\" - Data",
  "\"Captain, I wish to submit myself for disciplinary action.\" - Data",
  "\"There is a high degree of probability that the temporal rift is symmetrical, Captain.\" - Data",
  "\"It is green.\" - Data",
  "\"Captain, I do not believe you have the authority to promote me to the rank of admiral.\" - Data",
  "\"I see, sir. Oh - I see, sir!\" - Data",
  "\"Captain, I am not aware of Regulation 6.57.\" - Data",
  "\"If you met a double of yourself, would you have difficulty interacting with him?\" - Data",
  "\"Counselor - have you been promoted in my absence?\" - Data",
  "\"Most interesting. Could this be human joke number 663?\" - Data",
  "\"What is your condition, Doctor?\" - Data",
  "\"Yes, sir. I have found that humans often use small talk during awkward moments. Therefore, I have written a new subroutine for that purpose. How did I do?\" - Data",
  "\"You are attempting to bribe me.\" - Data",
  "\"Aye, sir.\" - Data",
  "\"It was six months later that you asked Commander Riker for his formal permission to court Counselor Troi.\" - Data",
  "\"I was never a boy.\" - Data",
  "\"I feel I must inform you, sir - you have also been infected by the intron virus.\" - Data",
  "\"I am apparently guilty of falsifying the Enterprise's records.\" - Data",
  "\"We were unable to retrieve him, sir. The Captain has been altered by the Borg.\" - Data",
  "\"'We are forced to abandon our starship. May she find her way without us.' Apparently she did, sir.\" - Data",
  "\"Sir - as my final duty as Acting Captain, I order you to bed. I shall do the same for all personnel.\" - Data",
  "\"Computer, eliminate program two.\" - Data",
  "\"Music, Professor.\" - Data",
  "\"Unlikely as it may sound, I believe the Enterprise may be forming an intelligence.\" - Data",
  "\"Query - 'Eager beaver'?\" - Data",
  "\"Sir, Lieutenant La Forge's eyes are far superior to human biological eyes, true?\" - Data",
  "\"I find myself in complete agreement with that assessment of the situation, sir.\" - Data",
  "\"Is that what is known as a 'poker face'?\" - Data",
  "\"I cannot allow you to continue.\" - Data",
  "\"I wonder. What would Dr. Freud say about the symbolism of devouring oneself?\" - Data",
  "\"I am superior, sir, in many ways. But I would gladly give it up to be human.\" - Data",
  "\"Perhaps this is a situation where excessive honesty can be detrimental.\" - Data",
  "\"Do you believe my suggested course of action should be followed?\" - Data",
  "\"I am trying to find two individuals with a snake.\" - Data",
  "\"There is no way anyone can prevent it, sir. At some future date, I will be transported back to 19th-century Earth, where I will die.\" - Data",
]

wesleyphrases = [
  "\"You'd let me do that? You'd let me throw away my career, just to save your neck?\" - Wesley",
  "\"No problem. Where women are concerned, I am in complete control!\" - Wesley",
  "\"Have you always been so disciplined?\" - Wesley",
  "\"We thought we could do it. We thought we could do anything. We were wrong. And Josh died.\" - Wesley",
  "\"What should I say? How do I act? What do I do?\" - Wesley",
  "\"I'm never gonna feel this way about anyone else.\" - Wesley",
  "\"Knowing that doesn't make it any easier.\" - Wesley",
  "\"I think I need to try something a little less... dangerous.\" - Wesley",
  "\"I think that's the first time anyone's used that particular word to describe me.\" - Wesley",
  "\"But on the Enterprise, you do that every day. Everyone depends on everyone else to protect them.\" - Wesley",
  "\"I thought there was nothing that could frighten a Klingon warrior.\" - Wesley",
  "\"I know. But this isn't any ship.\" - Wesley",
  "\"No, nothing! That's the third time you've asked me.\" - Wesley",
  "\"Sometimes. Sometimes it's more important to consider others before yourself.\" - Wesley",
  "\"Really? My very first friend was a warp coil.\" - Wesley",
  "\"Maybe there's more going on here than we thought. What if someone's trying to use the game for some purpose other than pleasure?\" - Wesley",
  "\"He'd listen to everyone's opinion and then make his own decision. But he's Captain Picard.\" - Wesley",
  "\"My parents had told me about the dangers of Starfleet missions. I knew it could happen.\" - Wesley",
  "\"Thank you, Captain Picard, thank you. And with that order dawns a brave new day for the Enterprise.\" - Wesley",
  "\"How can a chemical substance provide an escape?\" - Wesley",
  "\"It deals with high-energy plasma reactions with antimatter.\" - Wesley",
  "\"That was a great speech, Data. \"To know him is to love him is to know him... \"\" - Wesley",
  "\"Captain, we're receiving 285,000 hails.\" - Wesley",
  "\"Adults!\" - Wesley",
  "\"Parents.\" - Wesley",
  "\"It wasn't the Commander's phaser, it couldn't have been! There's another answer. We're just not seeing it.\" - Wesley",
  "\"Can you believe this smell?\" - Wesley",
  "\"I can't. I can't do it.\" - Wesley",
  "\"He wants the impossible!\" - Wesley",
]

guinanphrases = [
  "\"You know, you always drink alone. It wouldn't hurt you to seek out a little... companionship.\" - Guinan",
  "\"Every fiber in my being says this is a mistake. I can't explain it to myself, so I can't explain it to you. I only know that I'm right.
\" - Guinan",
  "\"Tasha, you're not supposed to be here.\" - Guinan",
  "\"That's the wonderful thing about crayons. They can take you to more places than a starship.\" - Guinan",
  "\"I don't think I like this sport.\" - Guinan",
  "\"You felt sorry for me. Look what it got you.\" - Guinan",
  "\"Aren't you gonna tell me you have to assimilate me?\" - Guinan",
  "\"I need to hear you say that you are sure... you're doing the right thing.\" - Guinan",
  "\"No.\" - Guinan",
  "\"Am I disturbing you?\" - Guinan",
  "\"I heard you got grounded.\" - Guinan",
  "\"My people encountered them a century ago. They destroyed our cities, scattered my people throughout the galaxy.\" - Guinan",
  "\"You know, I've never been to a formal inquiry.\" - Guinan",
  "\" Do I have to hit you with my fist before you tell me what happened?\" - Guinan",
  "\"I run a clean place.\" - Guinan",
  "\" A mother shapes her child in ways she doesn't even realize. Sometimes just by listening.\" - Guinan",
  "\"Actually, 'killed' would have been a better word.\" - Guinan",
  "\"Being able to make people laugh or being able to laugh is not the end-all and be-all of being human.\" - Guinan",
  "\"I'll see you in 500 years, Picard.\" - Guinan",
  "\"Dreams can be dangerous.\" - Guinan",
  "\"Shut up, kid!\" - Guinan",
  "\"You're a pitiful excuse for a human. The only way you're gonna survive is on the charity of others.\" - Guinan",
  "\"Just one of the boys, eh?\" - Guinan",
  "\"Seems human enough to me.\" - Guinan",
  "\"First it was a fish, and now it's a Mintonian sailing ship.\" - Guinan",
  "\"I knew, as long as that razor beast was around, nothing could hurt me.\" - Guinan",
  "\"You saw exactly what you wanted to see on the holodeck.\" - Guinan",
  "\"I've seen you laugh. I like it.\" - Guinan",
  "\"I get so tired of people coming in with their problems. They come in, they want a shoulder to cry on, and generally it turns out to be mine.\" - Guinan",
  "\"Human intuition and instinct are not always right. But they do make life interesting.\" - Guinan",
]

module.exports = (robot) ->
  robot.respond /worf me/i, (msg) ->
    msg.send msg.random worfphrases

  robot.respond /riker me/i, (msg) ->
    msg.send msg.random rikerphrases

  robot.respond /picard me/i, (msg) ->
    msg.send msg.random picardphrases

  robot.respond /data me/i, (msg) ->
    msg.send msg.random dataphrases

  robot.respond /wesley me/i, (msg) ->
    msg.send msg.random wesleyphrases

  robot.respond /guinan me/i, (msg) ->
    msg.send msg.random guinanphrases
